enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800
rpc-secret=ARIA2_SECRET
rpc-allow-origin-all=false
continue=true
max-concurrent-downloads=1
max-connection-per-server=8
split=8
min-split-size=16M
file-allocation=none
check-integrity=true
bt-save-metadata=true
bt-metadata-only=false
seed-time=0
seed-ratio=0
max-upload-limit=1K
listen-port=BT_PORT
dht-listen-port=BT_PORT
enable-dht=true
enable-dht6=false
enable-peer-exchange=true
bt-enable-lpd=false
follow-torrent=true
save-session=/var/lib/encrypted-mover/aria2.session
input-file=/var/lib/encrypted-mover/aria2.session
save-session-interval=60
console-log-level=notice
log=/var/log/encrypted-mover/aria2.log
log-level=notice
