/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
  }
}

// For TSX support
declare global {
  const ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
  const TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
}